= ChangeLog
:toc: auto

# Notice
All changes to this project for versions beyond v1.0.0 will be reflected here. For the initial release currently is a checklist, and bug catches + fixes from use cases.

== [0.9.9] - 2025-10-01


=== Bugs

- [] Bean injection quirk between NetBeans & command-line.
- [] Formatting of help splash text.
<<<<<<< HEAD
- [] Hangs if folder is not writable
=======
- [] Specifiy file path on command-line yields below, parsing is changing this somehow. Have this a parameter. What does CliParser see?
>>>>>>> c452fada49019ec6b0240244676a70cc96ac6984
....
2025-08-21 14:37:48 INFO  [ main -> org.tasktide.tasktide.TaskTide.main ]: Fetching the TaskTideServiceManager for 'Item Store' Repository
2025-08-21 14:37:48 INFO  [ main -> org.tasktide.tasktide.client.TaskTideClientUtility.initServiceManager ]: Configuring ItemStore ServiceManager
2025-08-21 14:37:48 DEBUG [ main -> org.tasktide.tasktide.client.TaskTideClientUtility.initItemStoreServiceManager ]: Repository FilePath is:   ''
2025-08-21 14:37:48 INFO  [ main -> org.tasktide.core.repository.itemstore_repo.ItemStoreRepositoryUtility.fetchItemStore ]: ItemStoreDirectory already exists under:   '/WORKITEM'
....
<<<<<<< HEAD
- [X] Casting error from specifiying file path on command-line.
        - Parsing saw argument this as boolean.
        - Reference class not set in configurer class, null get used must be boolean.
        - Resolving caught similar bugs across all config classes, decided to adjust builder.
- [] Hitting the skipping malformed line error for a list of work items in text file reset.
- [X] Client now hanging at initializing TaskTideServiceManager - typo in Configurer.
- [X] Stray target step being use on command-line arguments.
- [] Unit tests need to be pexecuted separately for nosql_repo, bubbles up as couchDB template ends up getting used for mongoDB.
=======


- [X] Client now hangs at initializing TaskTideServiceManager? And the DB path is not correct?
....
2025-08-20 18:32:28 INFO  [ main -> org.tasktide.tasktide.TaskTide.main ]: Fetching TaskTide configs
2025-08-20 18:32:28 INFO  [ main -> org.tasktide.tasktide.client.TaskTideClientUtility.fetchRepoType ]: Querying configured repo type:  'sqlite'
2025-08-20 18:32:28 INFO  [ main -> org.tasktide.tasktide.TaskTide.main ]: Fetching the TaskTideServiceManager for 'Item Store' Repository
2025-08-20 18:32:28 INFO  [ main -> org.tasktide.tasktide.client.TaskTideClientUtility.initServiceManager ]: Configuring ItemStore ServiceManager
2025-08-20 18:32:28 INFO  [ main -> org.tasktide.core.repository.itemstore_repo.ItemStoreRepositoryUtility.fetchItemStore ]: ItemStoreDirectory already exists under:   '/WORKITEM' 
....

- [] Stray target step being use on command-line arguments
- [] Unit tests need to be pexecuted separately for nosql_repo, bubbles up as couchDB template ends up getting used for mongoDB. Maybe 
>>>>>>> c452fada49019ec6b0240244676a70cc96ac6984
- [/] Unit test only bug for NoSQL Template Repository queries. Use manager instead test utility.
- [X] Sanity check from SQLiteDB that "Task Processing Follow Up" show right record in DB.
        /--> Not required, full story caught in log. Thread on token was processing, second thread eventually saw it was no longer ToDo and skipped.
- [X] Deprecated process executor.
- [X] In/output file must be in class path.
- [X] Internal config property for JNoSQL-Host, value pulled twice.
- [X] Mapping discordance of ItemId-Item Id between ManagerClient, and ManagerConfig.
- [X] ManagerAction query comparison too restrictive for what user would import.

=== Main Checklist

- []    1). Wrap-up code, repoistory and documentation for v1.
- []    2). Use-cases General, Bioinformatics, and AI with Super Mario Bros (after ConfigUtil handling).
- []    3). Paper write-up (initialize with repo docs, review after use-cases).
- []    4). Drop database files & old workflow engine from repo.
- []    5). Repository structured for JOSS.
- [/]   6). Docker compose.
- []    7). Kubectl config.


=== Code Checklist

A lot of the major aspects are done, or covered. These push towards a minimally functional v0.9.9, where a "once over" covers the v1. This push is neatness thing anticipating problems coming from use-case deployment.

- [/] Docker Compose.
- []  Test new ManagerActions.
- [] Logger messages DRY view on Debug, Info, Warn, Error.
- [] Apply ConfigUtil to TaskTideClient?
- [] Config validator.
- [] Engine cleanup - Logs, Service Shutdowns.
- [/] Config cleanup:
....
        - [/] Drop superfluous configs.
        - [X] Verify that --client can be dropped.
        - [X] Engine & Manager share model names.
        - [X] Input and Output file merged into Target File.
....
- [] Check over unit failed unit tests as they work independantly
....
        - [] Singleton not set for "container Id".
        - [] Engine error messages, and old unit tests missing SOA.
        - [/] Background jobs from ItemStore.
        - [X] TaskTideClient needs TestContainers.
....
- [X] Process Workflow as StepList (fine for now).
- [X] Apply container support to all required integration tests.
- [X] Reset WorkItem, and Task of WorkItem.
- [X] Enqueue a task, and append a task to a workitem.
- [X] Open collection name onto Item (ie Step on WorkItem).
- [X] Way to include "config" folder into zip.
- [X] Install helper script for TaskTide.
- [X] Display help message if required.
- [X] Support unit tests with docker container.
- [X] Load a target Microprofile config.
- [X] Update ItemStore to use DbTarget instead of overloading with master/prootype methods.
- [X] Fix RocksDB bug.
- [X] Initial Documentation.
- [X] UML & diagram per project (initial good until version hit).
- [X] Process list of Steps.
- [X] Functional client in NetBeans-IDE and command-line.
- [X] SQLite ItemStore.
- [X] JPA Repository.
- [X] TaskTide Architecture Diagrams.
