= ChangeLog
:toc: auto

# Notice
All changes to this project for versions beyond v1.0.0 will be reflected here. For the initial release currently is a checklist, and bug catches + fixes from use cases.

== [0.9.9] - 2025-10-01

=== Bugs
- [] Bean injection quirk between NetBeans & command-line.
- [] Formatting of help splash text.
- [] Specifiy file path on command-line yields below, parsing is changing this somehow. Have this a parameter
....

2025-08-20 19:22:19 DEBUG [ main -> org.tasktide.tasktide.configurer.GlobalConfig.filePath ]: Value for file path is '/scratch/bkenna/TaskTide/itemStore/client-args'
2025-08-20 18:28:34 INFO  [ main -> org.tasktide.tasktide.client.TaskTideClientUtility.initServiceManager ]: Configuring ItemStore ServiceManager
2025-08-20 18:28:34 FATAL [ main -> org.tasktide.tasktide.TaskTide.main ]: Exiting on fatal error:      'java.lang.ClassCastException: class java.lang.Boolean cannot be cast to class java.lang.String (java.lang.Boolean and java.lang.String are in module java.base of loader 'bootstrap')'
java.lang.ClassCastException: class java.lang.Boolean cannot be cast to class java.lang.String (java.lang.Boolean and java.lang.String are in module java.base of loader 'bootstrap')
        at org.tasktide.tasktide.client.TaskTideClientUtility.initItemStoreServiceManager(TaskTideClientUtility.java:207)
        at org.tasktide.tasktide.client.TaskTideClientUtility.initServiceManager(TaskTideClientUtility.java:164)
        at org.tasktide.tasktide.TaskTide.main(TaskTide.java:64)

// Thinks boolean is defined here, somehow it is changing?
org.tasktide.tasktide.client.TaskTideClientUtility.initItemStoreServiceManager
    /-> storeName = (String) configMap.getArgTree().getGlobalArguments().getArgument("File Path").getValue();


org.tasktide.tasktide.configurer.GlobalConfig{

    @ConfigProperty(name = "tasktide.core.repository.file-path", defaultValue = "myData")// RocksDB or Json
    private String filePath;

    public void filePath() {
        Argument<String> arg;
        arg = this.getArgumentBuilder()
            .withName("File Path")
            .withDescription("Specifies the file path for RocksDB/Json repository")
            .withShortFlag("-fp")
            .withLongFlag("--file-path")
            .withArgType(ArgumentType.ACTION)
        .build();
        
        this.filePath = this.getConfigValue("tasktide.core.repository.file-path", String.class, "");
        arg.setValue(this.filePath);
        this.getArgumentMap().putArgument(arg);
    }
}
....


- [X] Client now hangs at initializing TaskTideServiceManager? And the DB path is not correct?
....
2025-08-20 18:32:28 INFO  [ main -> org.tasktide.tasktide.TaskTide.main ]: Fetching TaskTide configs
2025-08-20 18:32:28 INFO  [ main -> org.tasktide.tasktide.client.TaskTideClientUtility.fetchRepoType ]: Querying configured repo type:  'sqlite'
2025-08-20 18:32:28 INFO  [ main -> org.tasktide.tasktide.TaskTide.main ]: Fetching the TaskTideServiceManager for 'Item Store' Repository
2025-08-20 18:32:28 INFO  [ main -> org.tasktide.tasktide.client.TaskTideClientUtility.initServiceManager ]: Configuring ItemStore ServiceManager
2025-08-20 18:32:28 INFO  [ main -> org.tasktide.core.repository.itemstore_repo.ItemStoreRepositoryUtility.fetchItemStore ]: ItemStoreDirectory already exists under:   '/WORKITEM' 
....

- [] Stray target step being use on command-line arguments
- [] Unit tests need to be pexecuted separately for nosql_repo, bubbles up as couchDB template ends up getting used for mongoDB. Maybe 
- [/] Unit test only bug for NoSQL Template Repository queries. Use manager instead test utility.
- [X] Sanity check from SQLiteDB that "Task Processing Follow Up" show right record in DB.

    /--> Not required, full story caught in log. Thread on token was processing, second thread eventually saw it was no longer ToDo and skipped.

- [X] Deprecated process executor
- [X] In/output file must be in class path.

- [X] Internal config property for JNoSQL, host value pulled twice.

....
2025-08-20 18:39:25 FATAL [ main -> org.tasktide.tasktide.TaskTide.main ]: Exiting on fatal error:      'java.util.NoSuchElementException: SRCFG00014: The config property tasktide.core.repository.jnosql.host is required but it could not be found in any config source'
java.util.NoSuchElementException: SRCFG00014: The config property tasktide.core.repository.jnosql.host is required but it could not be found in any config source
        at io.smallrye.config.SmallRyeConfig.convertValue(SmallRyeConfig.java:446)
        at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:391)
        at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:370)
        at org.tasktide.tasktide.configurer.dependent.JNoSQLConfigurer.nosqlHost(JNoSQLConfigurer.java:231)
        at org.tasktide.tasktide.configurer.dependent.JNoSQLConfigurer.initConfig(JNoSQLConfigurer.java:77)
        at org.tasktide.tasktide.configurer.GlobalConfig.initConfig(GlobalConfig.java:116)
        at org.tasktide.tasktide.configurer.GlobalConfig$Proxy$_$$_WeldClientProxy.initConfig(Unknown Source)
        at org.tasktide.tasktide.client.ClientConfigMap.parseConfigs(ClientConfigMap.java:52)
        at org.tasktide.tasktide.client.ClientConfigMap.addConfigs(ClientConfigMap.java:63)
        at org.tasktide.tasktide.TaskTide.main(TaskTide.java:51)
....

=== Main Checklist

- []    1). Wrap-up code, repoistory and documentation for v1.
- []    2). Use-cases General, Bioinformatics, and AI with Super Mario Bros (after ConfigUtil handling).
- []    3). Paper write-up (initialize with repo docs, review after use-cases).
- []    4). Drop database files & old workflow engine from repo.
- []    5). Repository structured for JOSS.
- [/]   6). Docker compose.
- []    7). Kubectl config.


=== Code Checklist

A lot of the major aspects are done, or covered. These push towards a minimally functional v0.9.9, where a "once over" covers the v1. This push is neatness thing anticipating problems coming from use-case deployment.

- [/] Docker Compose.
- [] Logger messages DRY view on Debug, Info, Warn, Error.
- [] Apply ConfigUtil to TaskTideClient?
- [] Config validator
- [] Engine cleanup - Logs, Service Shutdowns
- [/] Config cleanup:
....
        - [/] Drop superfluous configs.
        - [X] Engine & Manager share model names.
        - [X] Input and Output file merged into Target File.
....
- [] Check over unit failed unit tests as they work independantly
....
        - [] Singleton not set for "container Id".
        - [] Engine error messages, and old unit tests missing SOA.
        - [/] Background jobs from ItemStore.
        - [X] TaskTideClient needs TestContainers.
....
- [X] Process Workflow as StepList (fine for now).
- [X] Apply container support to all required integration tests.
- [X] Reset WorkItem, and Task of WorkItem
- [X] Enqueue a task, and append a task to a workitem.
- [X] Open collection name onto Item (ie Step on WorkItem).
- [X] Way to include "config" folder into zip.
- [X] Install helper script for TaskTide.
- [X] Display help message if required.
- [X] Support unit tests with docker container.
- [X] Load a target Microprofile config.
- [X] Update ItemStore to use DbTarget instead of overloading with master/prootype methods.
- [X] Fix RocksDB bug.
- [X] Initial Documentation.
- [X] UML & diagram per project (initial good until version hit).
- [X] Process list of Steps.
- [X] Functional client in NetBeans-IDE and command-line.
- [X] SQLite ItemStore.
- [X] JPA Repository.
- [X] TaskTide Architecture Diagrams.
