plugins {
    id 'java'
}

description = 'tasktide:engine'
group = 'org.tasktide.engine'
version = '0.9.5'

dependencies {

    // Project Core, and Manager Libs
    implementation project(':core')

    // Jakarta CDI
    implementation 'jakarta.enterprise:jakarta.enterprise.cdi-api:4.0.1'

    // JSON-B (de)Serialization
    implementation 'jakarta.json.bind:jakarta.json.bind-api:2.0.0' // For JSON-B serialization/deserialization
    implementation 'org.eclipse:yasson:3.0.3' // JSON-B implementation

    // Config
    implementation 'org.eclipse.microprofile.config:microprofile-config-api:2.0'

    // Log4J
    implementation 'org.apache.logging.log4j:log4j-api:2.20.0'
    implementation 'org.apache.logging.log4j:log4j-core:2.20.0'

    // Log4J
    implementation 'org.apache.logging.log4j:log4j-api:2.20.0'
    implementation 'org.apache.logging.log4j:log4j-core:2.20.0'

    // Use JUnit Jupiter for testing.
    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.1'
    testImplementation 'org.apache.logging.log4j:log4j-api:2.20.0'
    testImplementation 'org.apache.logging.log4j:log4j-core:2.20.0'

    // Jakarta-NoSQL
    testImplementation 'jakarta.nosql:jakarta.nosql-api:1.0.0'
    testImplementation "org.eclipse.jnosql.mapping:jnosql-mapping-document:1.1.8"
    testImplementation "org.eclipse.jnosql.databases:jnosql-couchdb:1.1.6"
    testImplementation project(":itemstore")
}


jar {
    archiveBaseName.set("tasktide-${project.name}")
    archiveVersion.set(version)
}