plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1' // Apply Shadow plugin for Fat JAR
}

description = 'tasktide:itemstore'
group = 'org.tasktide.itemstore'
version = '0.0.1'

dependencies {

    // SQLite JDBC driver
    implementation 'org.xerial:sqlite-jdbc:3.49.1.0'

    // RocksDB JNI (native bindings)
    implementation 'org.rocksdb:rocksdbjni:10.2.1'
}

jar {
    archiveBaseName.set("tasktide-${project.name}")
    archiveVersion.set(version)
}

tasks.register('fatJar', com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar) {
    archiveBaseName.set("tasktide-${project.name}")
    archiveVersion.set(version)
    archiveClassifier.set('all')
    configurations = [project.configurations.runtimeClasspath]
}

build.dependsOn fatJar