plugins {
    id 'java'
}

description = 'tasktide:itemstore'
version = providers.gradleProperty('itemstoreVersion').get()


dependencies {

    // Mutex sub-project
    implementation          project(":mutex")

    // SQLite JDBC driver
    implementation          'org.xerial:sqlite-jdbc:3.53.4.0'

    // RocksDB JNI (native bindings)
    implementation          'org.rocksdb:rocksdbjni:10.10.1.1'

    // Marshaller
    implementation          platform("com.fasterxml.jackson:jackson-bom:2.22.2")
    implementation          "com.fasterxml.jackson.datatype:jackson-datatype-jakarta-jsonp"
    //implementation        "tools.jackson.datatype:jackson-datatype-jakarta-jsonp:3.2.2"
}


// Define test scopes
def testTags = [
    "unit-tests": 'unit-itemstore',
    "integration-tests": 'integration-itemstore',
    "system-tests": 'system-itemstore'
]


// Define logging scope for all tests
tasks.withType(Test).configureEach {
    testLogging {
        showStandardStreams = true
        events "passed", "skipped", "failed", "standardOut", "standardError"
        exceptionFormat "full"
    }
}


// Register test under annotation scheme
testTags.each { name, tag ->
    tasks.register(name, Test) {
        group = 'itemstore-tests'
        description = "Run Parser ${name} tests (${tag})"
        testClassesDirs = sourceSets.test.output.classesDirs
        classpath = sourceSets.test.runtimeClasspath
        useJUnitPlatform {
            includeTags tag
        }
    }
}


jar {
    archiveBaseName.set("tasktide-${project.name}")
    archiveVersion.set(version)
}