@startuml

/'
################################################################
################################################################
##
## 1). TaskTide Client Application
##
################################################################
################################################################
'/


class org.tasktide.tasktide.TaskTide <<Application>> {
    .. **Attributes** ..
    - static Logger LOGGER

    .. **Supporting Methods** ..
    + static String fetchSplashString()
    + static void printSplash()
    + static CdiContainerProvider configureCdiInstance(CdiProviders)

    .. **Application Method** ..
    + static void main(String[])
}

org.tasktide.tasktide.TaskTide --> org.tasktide.tasktide.client.TaskTideClient
org.tasktide.tasktide.TaskTide --> org.tasktide.tasktide.containerprovider.CdiContainerProvider
org.tasktide.tasktide.TaskTide --> org.tasktide.core.manager.TaskTideServiceManager
class org.tasktide.core.manager.TaskTideServiceManager


/'
##################################################
##################################################
##
## a). TaskTide Client
##
##################################################
##################################################
'/

abstract class org.tasktide.tasktide.client.TaskTideClient <<abstract client>> #D7E7F7 {
  .. **Attributes** ..
  - TaskTideServiceManager taskTideManager;
  - ClientConfigMap config;

  .. **Construction** ..
  + TaskTideClient(TaskTideServiceManager, ClientConfigMap)

  .. **Implementation Wrapper** ..
  + void runClient()

  .. **Interface Method** ..
  + {abstract} void configureClient()
  + {abstract} void performClientTask()
  + {abstract} void cleanUp()
}


class org.tasktide.tasktide.client.TaskTideEngineClient <<extends client>> #C6DAF7 {
  .. **Attributes** ..
  - Logger LOGGER
  - TaskTideWorkerUnitProvider unitProvider;
  - int workItemThreads, itemTaskThreads
  - int workThreshold, taskThreshold;
  - TaskTideProcessor<WorkItem> processor;
  - TaskTideExecutor<WorkItem> workExec;
  - TaskTideEngineObserver<WorkItem> obs;

  .. **Construction** ..
  + TaskTideEngineClient(TaskTideServiceManager, ClientConfigMap)

  .. **TaskTideClient Implementation** ..
  + void runClient()
  + void configureClient()
  + void performClientTask()
  + void cleanUp()

  .. **TaskTideClient Decorators** ..
  - ExecutorService initializeAndConfigureExecutorServices()
  - TaskTideEngineObserver<WorkItem> configureWorkItemEngineObserverChain()
  - TaskTideExecutor<WorkItem> configureWorkItemExecutor(TaskTideEngineObserver<WorkItem>)
  - TaskTideProcessor<WorkItem> configureWorkItemProcessor(ExecutorService, TaskTideExecutor<WorkItem>)

  .. **Helper Methods** ..
  + void waitOnExecutorTrackerWorkItem(int, Logger)
  + int countNotActive(List<ItemTask>)
  + int countNonActive(List<WorkItem>)
  + void fetchExecutionTimes(List<ItemTask>, Logger)
  + void fetchExecutionTimesWorkItem(List<WorkItem>, Logger)
  + String mapToJsonString(Object)
}


class org.tasktide.tasktide.client.TaskTideManagerClient <<extends client>> #C6DAF7 {
  .. **Attributes** ..
  - Logger LOGGER
  - ArgumentMap argMap;

  .. **Construction** ..
  + TaskTideManagerClient(TaskTideServiceManager, ClientConfigMap)

  .. **TaskTideClient Implementation** ..
  + void runClient()
  + void configureClient()
  + void performClientTask()
  + void cleanUp()

  .. **TaskTideClient Decorators** ..
  - String parseFilePath(ManagerAction)
  - List<WorkItem> importJson(String)
  - List<WorkItem> importFile throws IOException
  - void handleImport()
}


enum org.tasktide.tasktide.client.TaskTideClientType #CCCCFF {
  .. **Enum Constants Implement Methods** ..
  GLOBAL
  ENGINE
  MANAGER

  .. **Strategy Methods** ..
  + abstract Class getConfigClass()
  + abstract TaskTideClient makeClient(TaskTideServiceManager, ClientConfigMap)
  + abstract boolean isClient(String)
  + abstract boolean isClient(TaskTideClientType)

  .. **Enum Methods** ..
  + static int indexOf(TaskTideClientType)
  + static int indexOf(String) 
  + static boolean hasQuery(String)
  + static TaskTideClientType get(String)
}


class org.tasktide.tasktide.client.TaskTideClientUtility #FFFFE0 {
  .. **Attributes** ..
  - static Logger LOGGER
  - static Jsonb JSON_PRETTY
  - static Jsonb JSON

  .. **Generic Utility Methods** ..
  + static String mapToJsonString(Object)

  .. **Aids construction** ..
  + static TaskTideClientType configureClient(ArgumentTree)
  + static RepositoryType fetchRepoType(ClientConfigMap)
  + static TaskTideServiceManager fetchManager(CdiContainerProvider, RepositoryType)
  + static TaskTideServiceManager fetchManager(Template)
}


class org.tasktide.tasktide.client.ClientConfigMap {
  .. **Attributes** ..
  - Map<TaskTideClientType, TaskTideConfigurer> configMap;
  - ArgumentTree argTree;
  - String[] argsIn;

  .. **Construction** ..
  + ClientConfigMap()

  .. **Provider Methods** ..
  + TaskTideConfigurer parseConfigs(CdiContainerProvider, TaskTideClientType)
  + void addConfigs(CdiContainerProvider)
  + TaskTideClientType whichClient()
}


org.tasktide.tasktide.client.TaskTideEngineClient --|> org.tasktide.tasktide.client.TaskTideClient
org.tasktide.tasktide.client.TaskTideManagerClient --|> org.tasktide.tasktide.client.TaskTideClient
org.tasktide.tasktide.client.TaskTideManagerClient --> org.tasktide.core.manager.ManagerAction
org.tasktide.tasktide.client.ClientConfigMap *-- org.tasktide.tasktide.client.TaskTideClient


/'
##################################################
##################################################
##
## b). TaskTide Configurer
##
##################################################
##################################################
'/

interface org.tasktide.tasktide.configurer.TaskTideConfigurer <<config>> #F8DE7E {
  + {abstract} void addToTree(ArgumentTree argTree)
  + {abstract} ArgumentMap getArgumentMap()
  + {abstract} ArgumentBuilder getArgumentBuilder()
  + {abstract} String getPath()
  + {abstract} Config getConfig()
  + {abstract} boolean parseCommandLineArguments(String[], ArgumentTree)
  + {abstract} initConfig(ArgumentTree)
}


abstract class org.tasktide.tasktide.configurer.AbstractConfigurer <<implements-config>> #FFE5B4 {
  .. **Attributes** ..
  - ArgumentMap argMap
  - String path
  - ArgumentBuilder argBuilder
  - Config config

  .. **Construction** ..
  + AbstractConfigurer(String)

  .. **TaskTideConfigurer Implementation** ..
  + void addToTree(ArgumentTree)
  + String getPath()
  + ArgumentMap getArgumentMap()
  + ArgumentBuilder getArgumentBuilder()
  + Config getConfig()
  + boolean parseCommandLineArguments(String[], ArgumentTree)
}


class org.tasktide.tasktide.configurer.GlobalConfig <<extends abstract-config>> #C6DAF7 {
  .. **Attributes** ..
  - String client, workflowsName, stepName, workItemName
  - String repositoryType, filePath, nosqlType
  - String nosqlProvider, nosqlProviderClass, nosqlPassword
  - String nosqlUser, nosqlHost, dateFormat
  - int tokenExpirationDays

  .. **Construction** ..
  + GlobalConfig()

  .. **TaskTideConfigurer Implementation** ..
  + void initConfig()

  .. **Microprofile Decorators** ..
  - void client()
}


class org.tasktide.tasktide.configurer.EngineConfig <<extends abstract-config>> #C6DAF7 {
  .. **Attributes** ..
  - int lockTime
  - int workItemThreads, workItemThreshold
  - int itemTaskThreads. itemTaskThreshold
  - int timeKeeperLevel
  - boolean timeKeeperOnStartCanFail
  - boolean timeKeeperOnProcessingCanFail
  - boolean timeKeeperOnEndCanFail
  - int timeKeeperWaitTime
  
  .. **Construction** ..
  + EngineConfig()

  .. **TaskTideConfigurer Implementation**. 
  + void initConfig()

  .. **Microprofile Decorators** ..
  - void lockTime()
  - void workItemThreads()
}


class org.tasktide.tasktide.configurer.ManagerConfig <<extends abstract-config>> #C6DAF7 {
  .. **Attributes** ..
  - String inputFile, outputFile, delimiter
  - String nestedDelimiter, method. targetStep

  .. **Construction** ..
  + ManagerConfig()

  .. **TaskTideConfigurer Implementation** ..
  + void initConfig()

  .. **Microprofile Decorators** ..
  - void inputFile()
  - void outputFile()
}


org.tasktide.tasktide.configurer.AbstractConfigurer ..|> org.tasktide.tasktide.configurer.TaskTideConfigurer
org.tasktide.tasktide.configurer.GlobalConfig --|> org.tasktide.tasktide.configurer.AbstractConfigurer
org.tasktide.tasktide.configurer.EngineConfig --|> org.tasktide.tasktide.configurer.AbstractConfigurer
org.tasktide.tasktide.configurer.ManagerConfig --|> org.tasktide.tasktide.configurer.AbstractConfigurer



/'
##################################################
##################################################
##
## c). TaskTide Command-Line Argument Parser
##
##################################################
##################################################
'/

class org.tasktide.tasktide.parser.ArgumentTree {
  .. **Attributes** ..
  - GenericTree<ArgumentMap> tree

  .. **Construction** ..
  + ArgumentTree(String delim)

  .. **Class Methods** ..
  + GenericTree<ArgumentMap> getTree() 
  + ArgumentMap getGlobalArguments()
  + ArgumentMap getActionArguments(String)
  + List<String> resolveActionPath(String[])
  + String<String> getVerboseHelp()
  + List<String> getGlobalHelp()
  + List<String> getActionHelp(String)
  + List<String> getActionHelp()
  - String formatHelpLines(Argument<?>)
}


class org.tasktide.tasktide.parser.CliParser {
  .. **Attributes** ..
  - ArgumentTree argTree
  - String[] argsIn
  - Map<String, Argument<?>> parsedArgs

  .. **Construction** ..
  + CliParser(ArgumentTree, String[])

  .. **Class Methods** ..
  + Map<String, Argument<?>> parse()
  - void parseFromMap(ArgumentMap)
  - int indexOf(Argument<?>)
  - boolean matchToArg(String, Argument<?>)
  - String fetchRawValue(int)
}


class org.tasktide.tasktide.parser.model.ArgumentMap {
  .. **Attributes** ..
  - Map<String, Argument<?>> args;

  .. **Construction** ..
  + ArgumentMap()

  .. **Class Methods** ..
  + Map<String, Argument<?>> getArgMap()
  + boolean putArgument(Argument<?>)
  + Argument<?> getArgument(String)
  + Map<String, Argument<?>> getArgumentMap()
}


class org.tasktide.tasktide.parser.model.Argument<<T>> {
  .. **Attributes** ..
  - T value
  - Class<T> refClass
  - String name, shortFlag, longFlag, description
  - ArgumentType argType

  .. **Construction** ..
  Argument(String, String, String, String, ArgumentType)
  Argument(T, String, String, String, String, ArgumentType, Class<T>)

  .. **Class Methods** ..
  + void parseValue(String)
  + ArgumentType getArgumentType()
  + String getLongFlag()
  + String getShortFlag()
  + String getDescription()
  + String getName()
  + Class<T> getRefClass()
  + T getValue()
  + void setValue(T)
}


enum org.tasktide.tasktide.parser.model.ArgumentType #CCCCFF {
  GLOBAL, ACTION
}


class org.tasktide.tasktide.parser.model.ArgumentBuilder {
  .. **Attributes** ..
  - String name, shortFlag, longFlag, description;
  - ArgumentType argType;
  
  // Optional properties handled generically
  - boolean withValue
  - Object value
  - Class<?> refClass

  .. **Building** ..
  + ArgumentBuilder withName(String)
  + ArgumentBuilder withShortFlag(String)
  + ArgumentBuilder withLongFlag(String)
  + ArgumentBuilder withDescription(String)
  + ArgumentBuilder withArgType(ArgumentType)
  + <T> ArgumentBuilder withValue(T, Class<T>)

  .. **Build** ..
  + <T> Argument<T> build()
}


class org.tasktide.tasktide.parser.model.GenericTree<<T>> {
  .. **Attributes** ..
  - GenericTreeNode<T> root
  - String delimiter

  .. **Construction** ..
  + GenericTree(delimiter)

  .. **Class Methods** ..
  + GenericTreeNode<T> getRoot()
  + void addChild(String, T )
  + GenericTreeNode<T> findByAddress(String)
  + T getDataForAddress(String)
  + boolean removeByAddress(String)
  + Map<String, GenericTreeNode<T>> getChildrenAtAddress(String)
  + Map<String, T> getChildrenDataAtAddress(String, String)
  + GenericTreeNode<T> findByData(T)
  + boolean containsData(T)
  + int size()
  + String subStringPathToFlag(String, String)

  .. **Recursive processing** ..
  - List<GenericTreeNode<T>> getPathToRoot(GenericTreeNode<T>)
  - Map<String, T> toAddressDataMap()
  - void collectAddressData(GenericTreeNode<T> current, Map<String, T> map)
  - int sizeRecursive(GenericTreeNode<T> current)
  - GenericTreeNode<T> recursiveFindByData(GenericTreeNode<T>, T)
  - boolean recursiveRemove(GenericTreeNode<T>, String[])
  - GenericTreeNode<T> recursiveGetByAddress(GenericTreeNode<T>, String)
  - void recursiveAdd(GenericTreeNode<T>, String, T)
}


class org.tasktide.tasktide.parser.model.GenericTreeNode<<T>> {
  .. **Attributes** ..
  - T data
  - final String address
  - GenericTreeNode<T> parent
  - Map<String, GenericTreeNode<T>> children

  .. **Construction** ..
  + GenericTreeNode(T, String)

  .. **Class Methods** ..
  + String getAddress()
  + T getData()
  + void setData(T data)
  + Map<String, GenericTreeNode<T>> getChildren()
  + GenericTreeNode<T> getParent()
  + void setParent(GenericTreeNode<T> parent)
  + boolean isLeaf()
  + boolean hasChild(String)
  + Set<String> listChildren()
  + boolean removeChild(String)
  + void clearChildren()
}


org.tasktide.tasktide.parser.model.GenericTreeNode --o org.tasktide.tasktide.parser.model.GenericTree
org.tasktide.tasktide.parser.model.ArgumentMap --o org.tasktide.tasktide.parser.ArgumentTree
org.tasktide.tasktide.parser.model.Argument --o org.tasktide.tasktide.parser.model.ArgumentMap
org.tasktide.tasktide.parser.model.GenericTree *-- org.tasktide.tasktide.parser.ArgumentTree
org.tasktide.tasktide.parser.ArgumentTree *-- org.tasktide.tasktide.parser.CliParser



/'
##################################################
##################################################
##
## d). TaskTide Container Provider
##
##################################################
##################################################
'/

enum org.tasktide.tasktide.containerprovider.CdiProviders #CCCCFF {
  .. **Enum Values** ..
  JAKARTA
  WELD
  QUARKUS

  .. **Strategy Methods** ..
  + {abstract} CdiContainerProvider<?> createProvider()
  + {abstract} boolean isProvider(String)
  + {abstract} boolean isProvider(CdiProviders)

  .. **Enum Methods** ..
  + static int indexOf(String)
  + static int indexOf(CdiProviders)
  + static boolean hasQuery(String)
  + static CdiProviders get(String)
}



interface org.tasktide.tasktide.containerprovider.CdiContainerProvider<T> <<container>> #F8DE7E {
  + void initialize()
  + void start()
  + void shutdown()
  + T getContainer()
  + < U> U getBean(Class<U>)
  + <V> void addBeanClass(Class<V>...)
  + <V> void addPackage(Class<V>...)
  + <V extends Extension> void addExtension(Class<V>...)
}


class org.tasktide.tasktide.containerprovider.SeContainerProvider<SeContainer> <<implements-container>> #FFE5B4 {
  .. **Attributes** ..
  - SeContainerInitializer initializer
  - SeContainer container
  
  .. **Implements Container Interface** ..
  + void initialize()
  + void start()
  + void shutdown()
  + SeContainer getContainer()
  + <T> getBean(Class<T>)
  + <V> void addBeanClass(Class<V>...)
  + <V> void addPackage(Class<V>...)
  + <V extends Extension> void addExtension(Class<V>...)
}


class org.tasktide.tasktide.containerprovider.WeldContainerProvider<WeldContainer> <<implements-container>> #FFE5B4 {
  .. **Attributes** ..
  - Weld initializer
  - WeldContainer container
  
  .. **Implements Container Interface** ..
  + void initialize()
  + void start()
  + void shutdown()
  + WeldContainer getContainer()
  + <T> getBean(Class<T>)
  + <V> void addBeanClass(Class<V>...)
  + <V> void addPackage(Class<V>...)
  + <V extends Extension> void addExtension(Class<V>...)
}


class org.tasktide.tasktide.containerprovider.QuarkusContainerProvider<ArcContainer> <<implements-container>> #FFE5B4 {
  .. **Attributes** ..
  - ArcContainer
  
  .. **Implements Container Interface** ..
  + void initialize()
  + void start()
  + void shutdown()
  + ArcContainer getContainer()
  + <T> getBean(Class<T>)
  + <V> void addBeanClass(Class<V>...)
  + <V> void addPackage(Class<V>...)
  + <V extends Extension> void addExtension(Class<V>...)
}


org.tasktide.tasktide.containerprovider.WeldContainerProvider --|> org.tasktide.tasktide.containerprovider.CdiContainerProvider
org.tasktide.tasktide.containerprovider.SeContainerProvider --|> org.tasktide.tasktide.containerprovider.CdiContainerProvider
org.tasktide.tasktide.containerprovider.QuarkusContainerProvider --|> org.tasktide.tasktide.containerprovider.CdiContainerProvider





/'
################################################################
################################################################
##
## 2). TaskTide ItemStore
##
################################################################
################################################################
'/


class org.tasktide.itemstore.Item<T> {
  .. **Attributes** ..
  - String id, state, payload
  
  .. **Construction** ..
  + Item()
  + Item(String, String, String)

  .. **Getters & Setters** ..
  + void setId(String)
  + void setState(String)
  + void setPayload(String)
  + String getId()
  + String setState()
  + String setPayload()
}


interface org.tasktide.itemstore.ItemStore <<itemstore>> #F8DE7E {
  + {abstract} String getStoreName()
  + {abstract} String getMasterFilePath()
  + {abstract} String getFilePath()
  + {abstract} String getDbDirectory()

  + {abstract} void saveItem(Item) throws Exception
  + {abstract} void saveItems(List<Item>) throws Exception
  + {abstract} void saveItemToMaster(Item) throws Exception
  + {abstract} void saveItemsToMaster(List<Item>) throws Exception
  + {abstract} List<Item> getAll(boolean)
  + {abstract} Item getById(String) throws Exception
  + {abstract} Item getByIdFromMaster(String) throws Exception
  + {abstract} List<Item> getItemsByState(String) throws Exception
  + {abstract} List<Item> getItemsByStateFromMaster(String) throws Exception;
  + {abstract} String getPayloadById(String)
  + {abstract} String getPayloadFromMaster(String)
  + {abstract} void syncToMaster(Item) throws Exception
  + {abstract} void syncToMaster(List<Item>) throws Exception
  + {abstract} void syncToMaster() throws Exception
  + {abstract} boolean cacheMaster() throws Exception
  + {abstract} boolean clearPrototype()
  + {abstract} boolean closeConn(DbTarget)
  + {abstract} boolean openConn(DbTarget)
  + {abstract} boolean delete(Item) throws Exception
  + {abstract} boolean deleteFromMaster(Item) throws Exception
}


abstract class org.tasktide.itemstore.stores.AbstractItemStore <<implements itemstore>> #FFE5B4 {
  - String storeName
  - Path dbDirectory, masterDB
  - Path protoDB, masterLock
  - FileChannel fileChannel
  - FileLock fileLock
  - Random RANDOM
}


enum org.tasktide.itemstore.stores.DbTarget #CCCCFF {
    .. **Enum Values** ..
    MASTER, PROTOTYPE, BOTH
}


class org.tasktide.itemstore.stores.RocksDBStore << extends itemstore >> #C6DAF7 {
    .. **Attributes** ..
    - RocksDB master, proto
    - Options options
    - ObjectMapper MAPPER

    .. **Construction** ..
    + RocksDBStore(String, String, String, String)

    .. **Decorator Methods** ..
    + Item fetchIteratorValue(RocksIterator);
    
    .. **ItemStore Implementation** ..
    + List<Item> getAll(boolean)
    + void saveItemToMaster(Item)
    + void saveItemsToMaster(List<Item>)
    + void saveItem(Item)
    + void saveItems(List<Item>)
    + Item getById(String)
    + Item getByIdFromMaster(String)
    + List<Item> getItemsByState(String)
    + List<Item> getItemsByStateFromMaster(String)
    + String getPayloadById(String)
    + String getPayloadById(String)
    + boolean closeConn(DbTarget)
    + boolean openConn(DbTarget)
    + boolean delete(Item)
    + boolean deleteFromMaster(Item)
}


org.tasktide.itemstore.stores.AbstractItemStore ..|> org.tasktide.itemstore.ItemStore
org.tasktide.itemstore.stores.RocksDBStore --|> org.tasktide.itemstore.stores.AbstractItemStore
org.tasktide.itemstore.ItemStore --o org.tasktide.itemstore.Item
org.tasktide.itemstore.stores.AbstractItemStore --> org.tasktide.itemstore.stores.DbTarget


/'
################################################################
################################################################
##
## 3). TaskTide CoreLib
##
################################################################
################################################################
'/


/'
##################################################
##################################################
##
## a). TaskTide Repository: RocksDb is actually an ItemStore like template
## consider its builder
##
##################################################
##################################################
'/

interface org.tasktide.core.TaskTideRepository<TaskTideModel> << repo >> #F8DE7E {
  + {abstract} Optional<T> findById(String)
  + {abstract} T insertModel(T)
  + {abstract} T updateModel(T)
  + {abstract} boolean deleteModel(String)
  + {abstract} List<T> findByField(String, Object)
  + {abstract} List<T> findAll()
  + {abstract} int save()
  + {abstract} List<T> load()
  + {abstract} boolean extendModel(List<T>)
  + {abstract} Map<String, String> getRepositoryMetaData()
}


abstract class org.tasktide.core.repository.TemplateRepository<TaskTideModel> <<implements repo>> #FFE5B4 {
  .. **Attributes** ..
  - Template template
  - Class<T> COLLECTION_CLASS
  - String collectionName
  - RepositoryType repoType

  .. **Construction** ..
  + TemplateRepository(Template, Class<T>, String)

  .. **TaskTideRepository Implementation** ..
  + Map<String, String> getRepositoryMetaData()
  + Optional<T> findById(String)
  + T insertModel(T)
  + T updateModel(T)
  + boolean deleteModel(String)
  + List<T> findByField(String, Object)
  + List<T> findAll()
  + int save()
  + List<T> load()

  .. **Class Methods** ..
  + Class<T> getCollectionClass()
  + String getCollectionName()
  + RepositoryType getRepoType()
}


class org.tasktide.core.repository.nosql_repo.TemplateWorkflowRepository<Workflow> << extends template-repo >> #C6DAF7 {
  + TemplateWorkflowRepository(Template, String)
}
class org.tasktide.core.repository.nosql_repo.TemplateStepRepository<Step> << extends template-repo >> #C6DAF7 {
  + TemplateStepRepository(Template, String)
}
class org.tasktide.core.repository.nosql_repo.TemplateWorkItemRepository<WorkItem> << extends template-repo >> #C6DAF7 {
  + TemplateWorkItemRepository(Template, String)
}


abstract class org.tasktide.core.repository.JsonRepository<TaskTideModel> <<implements repo>> #FFE5B4 {
  .. **Attributes** ..
  - List<T> data
  - Class<T> COLLECTION_CLASS
  - String collectionName
  - RepositoryType repoType

  .. **Construction** ..
  + JsonRepository(List<T>, Class<T>, String)

  .. **TaskTideRepository Implementation** ..
  + Map<String, String> getRepositoryMetaData()
  + Optional<T> findById(String)
  + T insertModel(T)
  + T updateModel(T)
  + boolean deleteModel(String)
  + List<T> findByField(String, Object)
  + List<T> findAll()
  + int save()
  + List<T> load()

  .. **Class Methods** ..
  + Class<T> getCollectionClass()
  + String getCollectionName()
  + RepositoryType getRepoType()
}


class org.tasktide.core.repository.json_repo.JsonWorkflowRepository<Workflow> << extends json-repo >> #C6DAF7 {
  + JsonWorkflowRepository(List<Workflow>, String)
}
class org.tasktide.core.repository.json_repo.JsonStepRepository<Step> << extends json-repo >> #C6DAF7 {
  + JsonStepRepository(List<Step>, String)
}
class org.tasktide.core.repository.json_repo.JsonWorkItemRepository<WorkItem> << extends json-repo >> #C6DAF7 {
  + JsonWorkItemRepository(List<WorkItem>, String)
}


abstract class org.tasktide.core.repository.RocksDbRepository<TaskTideModel> <<implements repo>> #FFE5B4 {
  .. **Attributes** ..
  - ItemStore data
  - Class<T> COLLECTION_CLASS
  - String collectionName
  - RepositoryType repoType
  - Jsonb JSON_BUILDER

  .. **Construction** ..
  + RocksDbRepository(ItemStore, Class<T>, String)

  .. **TaskTideRepository Implementation** ..
  + Map<String, String> getRepositoryMetaData()
  + Optional<T> findById(String)
  + T insertModel(T)
  + T updateModel(T)
  + boolean deleteModel(String)
  + List<T> findByField(String, Object)
  + List<T> findAll()
  + int save()
  + List<T> load()

  .. **Class Methods** ..
  + Class<T> getCollectionClass()
  + String getCollectionName()
  + RepositoryType getRepoType()

  - Item<T> toItem(T)
  - T toModel(Item)
}

class org.tasktide.core.repository.rocksdb.RocksDbWorkflowRepository<Workflow> << extends rocks-repo >> #C6DAF7 {
  + RocksDbWorkflowRepository(ItemStore, String)
}
class org.tasktide.core.repository.rocksdb.RocksDbStepRepository<Step> << extends rocks-repo >> #C6DAF7 {
  + RocksDbStepRepository(ItemStore, String)
}
class org.tasktide.core.repository.rocksdb.RocksDbWorkItemRepository<WorkItem> << extends rocks-repo >> #C6DAF7 {
  + RocksDbWorkItemRepository(ItemStore, String)
}


enum org.tasktide.core.repository.RepositoryType #CCCCFF {
  .. **Attributes** ..
  NOSQL
  ROCKSDB
  JSON

  .. **Strategy Methods** ..
  + boolean isRepository(String)
  + boolean isRepository(RepositoryType)
  + <T> TaskTideRepository<T> createRepository(Class<T>, Object, String)

  .. **Enum Methods** ..
  + static int indexOf(String)
  + static boolean hasType(String)
}


org.tasktide.core.repository.TemplateRepository ..|> org.tasktide.core.TaskTideRepository
org.tasktide.core.repository.RocksDbRepository ..|> org.tasktide.core.TaskTideRepository
org.tasktide.core.repository.JsonRepository ..|> org.tasktide.core.TaskTideRepository


org.tasktide.core.repository.nosql_repo.TemplateWorkflowRepository --|> org.tasktide.core.repository.TemplateRepository
org.tasktide.core.repository.nosql_repo.TemplateStepRepository --|> org.tasktide.core.repository.TemplateRepository
org.tasktide.core.repository.nosql_repo.TemplateWorkItemRepository --|> org.tasktide.core.repository.TemplateRepository


org.tasktide.core.repository.rocksdb.RocksDbWorkflowRepository --|> org.tasktide.core.repository.RocksDbRepository
org.tasktide.core.repository.rocksdb.RocksDbStepRepository --|> org.tasktide.core.repository.RocksDbRepository
org.tasktide.core.repository.rocksdb.RocksDbWorkItemRepository --|> org.tasktide.core.repository.RocksDbRepository


org.tasktide.core.repository.json_repo.JsonWorkflowRepository --|> org.tasktide.core.repository.JsonRepository
org.tasktide.core.repository.json_repo.JsonStepRepository --|> org.tasktide.core.repository.JsonRepository
org.tasktide.core.repository.json_repo.JsonWorkItemRepository --|> org.tasktide.core.repository.JsonRepository



/'
##################################################
##################################################
##
## b). TaskTide Service: Use get method instead of delegation
##
##################################################
##################################################
'/

interface org.tasktide.core.TaskTideMapper #F8DE7E {
  + {abstract} List< U > getThroughLink(TaskTide Service< U >, T)
}

interface org.tasktide.core.TaskTideService<TaskTideModel> #F8DE7E {
  + {abstract} T appendModel(T)
  + {abstract} List<T> viewByFieldValue(String, Object)
  + {abstract} List<T> viewAll()
  + {abstract} fetchById(String)
  + {abstract} boolean dropById(String)
  + {abstract} T updateModel(T)
  + {abstract} boolean extendModel(List<T>)
  + {abstract} int save()
  + {abstract}TaskTideRepository<T> getRepo()
}


class org.tasktide.core.services.WorkflowService<Workflow> << implements TaskTideMapper, TaskTideService >> #FFE5B4 {
  .. **Attributes** ..
  - TaskTideRepository<Workflow> repo

  .. **Construction** ..
  + WorkflowService(TaskTideRepository<Workflow>)

  .. **TaskTideService Implementation** ..
  + Workflow appendModel(Workflow)
  + List<Workflow> viewByFieldValue(String, Object)
  + List<Workflow> viewAll()
  + fetchById(String)
  + boolean dropById(String)
  + Workflow updateModel(Workflow)
  + boolean extendModel(List<Workflow>)
  + int save()
  + TaskTideRepository<Workflow> getRepo()
  + List<Step> getThroughLink(TaskTideService<Step>, Workflow)
}


class org.tasktide.core.services.StepService<Step> << implements TaskTideMapper, TaskTideService >> #FFE5B4 {
  .. **Attributes** ..
  - TaskTideRepository<Step> repo

  .. **Construction** ..
  + StepService(TaskTideRepository<Step>)

  .. **TaskTideService Implementation** ..
  + Step appendModel(Step)
  + List<Step> viewByFieldValue(String, Object)
  + List<Step> viewAll()
  + fetchById(String)
  + boolean dropById(String)
  + Step updateModel(Step)
  + boolean extendModel(List<Step>)
  + int save()
  + TaskTideRepository<Step> getRepo()
  + List<WorkItem> getThroughLink(TaskTideService<WorkItem>, Step)
}


class org.tasktide.core.services.WorkItemService<WorkItem> << implements TaskTideMapper, TaskTideService >> #FFE5B4 {
  .. **Attributes** ..
  - TaskTideRepository<WorkItem> repo

  .. **Construction** ..
  + StepService(TaskTideRepository<WorkItem>)

  .. **TaskTideService Implementation** ..
  + WorkItem appendModel(WorkItem)
  + List<WorkItem> viewByFieldValue(String, Object)
  + List<WorkItem> viewAll()
  + fetchById(String)
  + boolean dropById(String)
  + WorkItem updateModel(WorkItem)
  + boolean extendModel(List<WorkItem>)
  + int save()
  + TaskTideRepository<WorkItem> getRepo()
  + List<Step> getThroughLink(TaskTideService<Step>, WorkItem)
}


class org.tasktide.core.services.ServiceFactory {
  + static TaskTideService<WorkItem> makeWorkItemService(RepositoryType, Object, String, int, String)
  + static WorkItemService makeWorkItemService(TaskTideRepository<WorkItem>, int, String)
  + static WorkItemService makeWorkItemService(TaskTideRepository<WorkItem>)
  + static TaskTideService<WorkItem> makeWorkItemService(RepositoryType, Object, String)
  + static StepService makeStepService(TaskTideRepository<Step>)
  + static TaskTideService<Step> makeStepService(RepositoryType, Object, String)
  + static WorkflowService makeWorkflowService(TaskTideRepository<Workflow>)
  + static TaskTideService<Workflow> makeWorkflowService(RepositoryType, Object, String)
}

org.tasktide.core.services.WorkItemService ..|> org.tasktide.core.TaskTideService
org.tasktide.core.services.StepService ..|> org.tasktide.core.TaskTideService
org.tasktide.core.services.WorkflowService ..|> org.tasktide.core.TaskTideService

org.tasktide.core.services.WorkItemService ..|> org.tasktide.core.TaskTideMapper
org.tasktide.core.services.StepService ..|> org.tasktide.core.TaskTideMapper
org.tasktide.core.services.WorkflowService ..|> org.tasktide.core.TaskTideMapper

org.tasktide.core.services.ServiceFactory --> org.tasktide.core.services.WorkItemService
org.tasktide.core.services.ServiceFactory --> org.tasktide.core.services.WorkflowService
org.tasktide.core.services.ServiceFactory --> org.tasktide.core.services.StepService

org.tasktide.core.TaskTideService --> org.tasktide.core.TaskTideRepository
org.tasktide.core.TaskTideService --> org.tasktide.core.TaskTideModel
org.tasktide.core.TaskTideRepository --> org.tasktide.core.TaskTideModel

/'
##################################################
##################################################
##
## c). TaskTide Model
##
##################################################
##################################################
'/

interface org.tasktide.core.TaskTideModel<TaskTideModel> #F8DE7E {
  + String toJson()
  + String getId()
  + String getState()
  + Object getValueFromField(String)
}


entity org.tasktide.core.model.workitem.WorkItem <<implements TaskTideModel >> #FFE5B4 {
  .. **Attributes** ..
  - String id, itemName, lockId, stepName
  - long lockDate, doneDate
  - int taskCount, taskDone
  - ItemType itemType
  - ItemState itemState
  - Workload workload
  
  .. **Construction** ..
  + WorkItem()
  + WorkItem(< All Attributes >)

  .. **Methods** ..
  + boolean addTask(ItemTask)
  + boolean dropTask(ItemTask)
  + int getWorkloadSize()
  + Map<ItemState, Integer? summarizeByStates()
  + Map<ItemState, List<ItemTask>> fetchByStates()
  + void setTaskCounts()
  
  .. **TaskTideModel Implementation** ..
  + String toJson()
  + String getId()
  + String getState()
  + Object getValueFromField(String)

  .. **// Getters & Setters //** ..
}



entity org.tasktide.core.model.workitem.Workload<<Embedded>> {
    .. **Attributes** ..
    - String workloadId
    - Map<String, ItemTask> workload
    - ItemType itemType

    .. **Construction** ..
    + Workload()
    + Workload(String, Map<String, ItemTask>, ItemType)

    .. **Class Methods** ..
    + boolean addTask(String, ItemTask)
    + boolean addTask(ItemTask)
    + ItemTask getTask(String)
    + boolean dropTask(String)
    + boolean dropTask(ItemTask)
    + Map<TaskState, Integer> summarizeWorkload()
    + Mqp<TaskState, List<ItemTask>> fetchByState()
    + long getLatestDone()
    + long getEarliestDone()
    + int getWorkloadSize()
    + String getId()
    
    .. **// Getters & Setters //** ..
}



entity org.tasktide.core.model.task.ItemTask <<Embedded implements TaskTideModel >> #FFE5B4 {
    .. **Attributes ** ..
    - String itemTaskId, taskName, task
    - TaskState taskState
    - TaskLogging taskLog

    .. **Construction** ..
    + TaskLogging()
    + TaskLogging(< All Attributes >)

    .. **Class Methods** ..
    + String toJsonString()
    + String toJsonDoc()

    .. **TaskTideModel Implementation** ..
    + String toJson()
    + String getId()
    + String getState()
    + Object getValueFromField(String)

    .. **// Getters & Setters //** ..
}



entity org.tasktide.core.model.task.ProcessLog<<Embedded>> {
    .. **Attributes** ..
    - String procId
    - String[] stdout, stderr

    .. **Construction** ..
    + ProcessLog()
    + ProcessLog(< All Attributes >)

    .. **Class Methods** ..
    + String toJsonString()
    + String toJsonDoc()

    .. **//Getters & Setters//** ..
}



entity org.tasktide.core.model.task.TaskLogging<<Embedded>> {
    .. **Attributes** ..
    - String taskLogId
    - long procId
    - ProcessLog procLog
    - long startTime, endTime, cpuDuration
    - String threadName
    - int exitCode

    .. **Construction** ..
    + TaskLogging()
    + TaskLogging(< All Attributes >)

    .. **Class Methods** ..
    + String toJsonString()
    + String toJsonDoc()

    .. **//Getters & Setters//** ..
}



entity org.tasktide.core.model.task.TaskState #CCCCFF {
    .. **Enum Values** ..
    PENDING
    ACTIVE
    ERROR
    TIME_KEEPER
    COMPLETE

    .. **Value Methods** ..
    + {abstract} boolean isState(String)
    + {abstract+ boolean isState(TaskState)
    + {abstract} ItemState mapToItemState()

    .. **Enum Methods** ..
    + static int indexOf(String)
    + static boole hasType(String)
}



entity org.tasktide.core.model.collection.Step<<Entity Implements TaskTideModel>> #FFE5B4 {
    .. **Attributes** ..
    - String stepId, stepName
    - TaskState taskState
    - int stepCount, stepsLocked, stepsDone
    - int stepsError, stepsToDo

    .. **Construction** ..
    + Step()
    + Step(< All Attributes >)

    .. **Class Methods** ..
    + StateSummary<ItemState> summarizeByState()
    + void setStateCounts(StateSummary<ItemState>)
    + String toJsonString()
    + String toJsonDoc()

    .. **TaskTideModel Implementation** ..
    + Object getValueFromField(String) 
    + String getState()
    + String toJson()
    + String getId()

    .. **//Getters & Setters//** ..
}



entity org.tasktide.core.model.collection.Workflow<<Entity Implements TaskTideModel>> #FFE5B4 {
    .. **Attributes** ..
    - String workflowId, workflowName
    - Map<String, Step> worklowSteps

    .. **Construction** ..
    + Workflow()
    + Workflow(< All Attributes >)

    .. **Class Methods** ..
    + StateSummary<ItemState> summarizeByState()
    + void setStateCounts(StateSummary<ItemState>)
    + String toJsonString()
    + String toJsonDoc()

    .. **TaskTideModel Implementation** ..
    + Object getValueFromField(String) 
    + String getState()
    + String toJson()
    + String getId()

    .. **//Getters & Setters//** ..
}


org.tasktide.core.model.task.ItemTask ..|> org.tasktide.core.TaskTideModel
org.tasktide.core.model.workitem.WorkItem ..|> org.tasktide.core.TaskTideModel
org.tasktide.core.model.collection.Step ..|> org.tasktide.core.TaskTideModel
org.tasktide.core.model.collection.Workflow ..|> org.tasktide.core.TaskTideModel


org.tasktide.core.model.workitem.Workload *-- org.tasktide.core.model.workitem.WorkItem
org.tasktide.core.model.workitem.Workload --o org.tasktide.core.model.task.ItemTask
org.tasktide.core.model.collection.Step --o org.tasktide.core.model.collection.Workflow
org.tasktide.core.model.task.TaskLogging *-- org.tasktide.core.model.task.ItemTask
org.tasktide.core.model.task.ProcessLog *-- org.tasktide.core.model.task.TaskLogging


/'
##################################################
##################################################
##
## c). Manager
##
##################################################
##################################################
'/


' Aggregates TaskTideServices
class org.tasktide.core.manager.TaskTideServiceManager {
    .. **Attributes** ..
    - TaskTideService<WorkItem> workItemService
    - TaskTideService<Step> stepService
    - TaskTideService<Workflow> workflowService

    .. **Construction** ..
    + TaskTideServiceManager(< All Attributes >)

    .. **Class Methods** ..
    + TaskTideService<WorkItem> getWorkItemService()
    + TaskTideService<Step> getStepService()
    + TaskTideService<Workflow> getWorkflowService()
}


enum org.tasktide.core.manager.ManagerAction #CCCCFF {
    .. **Attributes** ..
    IMPORT
    EXPORT

    .. **Value Methods**..
    + {abstract} boolean isManagerAction(String)
    + {abstract} boolean isMAnagerAction(ManagerAction)

    .. **Enum Methods** ..
    + static boolean hasQuery(String)
    + static int indexOf(String)
    + static ManagerAction get(String)
}



class org.tasktide.core.manager.ManagerTask {
    .. **Attributes** ..
    - String taskName, taskScript
    - ItemTaskBuilder itemTaskBuilder
    - ProcessLogBuilder procLogBuilder;
    - TaskLoggingBuilder taskLogBuilder
    - Utils utils

    .. **Class Methods** ..
    + Map<String, String> asMap()
    + ItemTask asItemTask()
    
    .. **Represent as JSON** ..
    + String toJsonString()
    + String toJsonDoc();

    .. **//Getters & Setters//** ..
}


class org.tasktide.core.manager.BuilderUtility #FFFFE0 {
    .. **Attributes** ..
    - TaskGenerator taskGenerator
    - Utils utils

    .. **Class Methods** ..
    + static ProcessLog makeEmptyProcessLog()
    + static ProcessLog buildProcessLog(String[], String[])
    + static ProcessLog buildProcessLog(String, String[], String[]

    + static TaskLogging buildEmptyTaskLogging()
    + static TaskLogging buildTaskLogging(ProcessLog)
    + static TaskLogging buildTaskLogging(ProcessLog, Process)
    + static TaskLogging buildTaskLogging(String, ProcessLog)

    + static Workload buildEmptyWorkload()

 )
}


org.tasktide.core.manager.TaskTideServiceManager *-- org.tasktide.core.services.WorkItemService
org.tasktide.core.manager.TaskTideServiceManager *-- org.tasktide.core.services.StepService
org.tasktide.core.manager.TaskTideServiceManager *-- org.tasktide.core.services.WorkflowService
org.tasktide.core.manager.TaskTideServiceManager --> org.tasktide.core.services.ServiceFactory



/'
##################################################
##################################################
##
## d). Supporting
##
##################################################
##################################################
'/


class org.tasktide.core.supporting.DateUtility #FFFFE0 {
    .. **Attributes** ..
    - DateFormat DATE_FORMAT
    - int EXPIRATION_DAYS

    .. **Class Methods** ..
    + long getTimeTaken(Date, Date)
    + long getDateLong*(
    + Date getDate()
    + Date getDateFromTime(long)
    + String formatDate(Date)
    + String getNoswString()
    + String getDateString(Date date)
    + Date parseDate(String)
    + Date getExpirationForDate(Date)
    + boolean hasExceeded(Date)
}


class org.tasktide.core.supporting.Utils #FFFFE0 {
    .. **Attributes** ..
    - Random rand
    - Charset charset
    - DateUtility dateUtils

    .. **Class Methods** ..
    + String generateSalt()
    + UUID generateUUID(String)
    + String stringToHex(String)
    + String generateToken()
    + String generateSHA_HASH(String, String)
    + int getRandomInt(int)
    + boolean waitSeconds(int)
    + boolean waitMiliseconds(int)
    + Random getRandom()
    + Charset getCharset()
    + DateUtility getDateUtility()
}



/'
################################################################
################################################################
##
## 3). TaskTide Engine
##
################################################################
################################################################
'/


/'
##################################################
##################################################
##
## a). TaskTideProcessor
##
##################################################
##################################################
'/


interface org.tasktide.engine.worker.TaskTideWorkerUnit #F8DE7E {
    .. **Marker Interface**..
}



abstract class org.tasktide.engine.worker.processor.TaskTideProcessor<T extends TaskTideModel> <<implements TaskTideWorkerUnit>> #D7E7F7 {
    .. **Attributes** ..
    - List<T> workload
    # Logger logger
    # int threshold
    # ExecutorService executorService

    .. **Construction**..
    + TaskTideProcessor(< All Attributes >)

    .. **Abstraction Processing**..
    + void process()
    # Future<?> submitSubTask(List<T>)
    + void processChunks(List<T>)
    # Future<?> submitParallelSubTask(List<T>)
    - void waitForAll(List<Future<?>>)
    - void submitParallelChunks(List<T>

    .. **Interface Methods** ..
    # {abstract} List<List<T>> parallelChunks(List<T>)
    # {abstract} void addTasksToTracker(List<T>, Future)
    # {abstract} TaskTideProcessor<T> newSubProcessor(List<T>)
    # {abstract} TaskTideExecutor<T> getExecutor()
}



class org.tasktide.engine.worker.processor.WorkItemProcessor <<extends TaskTideProcessor<WorkItem>>> #C6DAF7 {
    .. **Attributes** ..
    - WorkItemExecutor worker

    .. **Construction** ..
    WorkItemProcessor(< All Attributes >)

    .. **Interface Implementation** ..
    # TaskTideProcessor<WorkItem> newSubProcessor(List<WorkItem>)
    # TaskTideExecutor<WorkItem> getExecutor()
    # void addTasksToTracker(List<WorkItem>, Future)
    # List<List<WorkItem>> parallelChunks(List<WorkItem>)
}


class org.tasktide.engine.worker.processor.ItemTaskProcessor <<extends TaskTideProcessor<ItemTask>>> #C6DAF7 {
    .. **Attributes** ..
    - ItemTaskExecutor worker

    .. **Construction** ..
    ItemTaskProcessor(< All Attributes >)

    .. **Interface Implementation** ..
    # TaskTideProcessor<ItemTask> newSubProcessor(List<ItemTask>)
    # TaskTideExecutor<ItemTask> getExecutor()
    # void addTasksToTracker(List<ItemTaskItemTask>, Future)
    # List<List<ItemTask>> parallelChunks(List<ItemTask>)
}



org.tasktide.engine.worker.processor.TaskTideProcessor ..|> org.tasktide.engine.worker.TaskTideWorkerUnit
org.tasktide.engine.worker.processor.WorkItemProcessor --|> org.tasktide.engine.worker.processor.TaskTideProcessor
org.tasktide.engine.worker.processor.ItemTaskProcessor --|> org.tasktide.engine.worker.processor.TaskTideProcessor

org.tasktide.engine.worker.processor.WorkItemProcessor --> org.tasktide.engine.worker.executor.WorkItemExecutor
org.tasktide.engine.worker.processor.ItemTaskProcessor --> org.tasktide.engine.worker.executor.ItemTaskExecutor


/'
##################################################
##################################################
##
## b). Executor
##
##################################################
##################################################
'/


abstract class org.tasktide.engine.worker.executor.TaskTideExecutor<T extends TaskTideModel<T>> <<implements TaskTideWorkerUnit>> #D7E7F7 {
    .. **Attributes** ..
    # Logger logger
    # AtomeInteger sharedCounter
    # ProcessExecutor processExecutor
    # int processCount
    # TaskTideEngineObserver<T> observer

    .. **Construction** ..
    TaskTideExecutor(< All Attributes >)

    .. **Abstraction Processing** ..
    + void runTasks(List<T>)
    + void handleFailure(T, Exception)
    + int getProcessCount()
    + void incrementCount()
    + void decrementCout()
    + static int globalCount()

    .. **Interface Methods** ..
    # boolean executeTask(T) throws IOException, InterruptException
}



class org.tasktide.engine.worker.executor.WorkItemExecutor<< extends TaskTideExecutor<WorkItem>> #C6DAF7 {
    .. **Attributes** ..
    - int nThreads, taskThreshold
    - TaskTideWorkerUnitProvider unitProvider

    .. **Construction** ..
    WorkItemExecutor(< All Attributes >)

    .. **Class Methods** ..
    + int getnThreads()
    + int getTaskThreshold()
    + TaskTideProcessor<ItemTask> provideProcessor(WorkItem)

    .. **Interface Implementation** ..
    # executeTask(WorkItem) throws IOException, InterruptException
}


class org.tasktide.engine.worker.executor.ItemTaskExecutor<< extends TaskTideExecutor<ItemTask>> #C6DAF7 {
    .. **Construction** ..
    ItemTaskExecutor(< All Attributes >)

    .. **Interface Implementation** ..
    # executeTask(WorkItem) throws IOException, InterruptException
}


class org.tasktide.engine.worker.executor.ProcessExecutor {
    .. **Attributes** ..
    - Logger logger
    - DateUtility dateUtils

    .. **Construction** ..
    ProcessExecutor(String dateFormat, int expirationDays)

    .. **Class Methods** ..
    + TaskLogging execute(String) throws IOException, InterruptException
    + String[] readStream(InputStream) throws IOException
    + ProcessLog buildProcessLog(Process) throws IOException
    + TaskLogging buildTaskLogging(Process, ProcessLog, long, long)
}


org.tasktide.engine.worker.executor.TaskTideExecutor ..|> org.tasktide.engine.worker.TaskTideWorkerUnit
org.tasktide.engine.worker.executor.WorkItemExecutor --|> org.tasktide.engine.worker.executor.TaskTideExecutor
org.tasktide.engine.worker.executor.ItemTaskExecutor --|> org.tasktide.engine.worker.executor.TaskTideExecutor
org.tasktide.engine.worker.executor.TaskTideExecutor *-- org.tasktide.engine.worker.executor.ProcessExecutor

org.tasktide.engine.worker.executor.WorkItemExecutor --> org.tasktide.engine.worker.executor.ItemTaskExecutor


/'
##################################################
##################################################
##
## b). Observer
##
##################################################
##################################################
'/


interface org.tasktide.engine.observer.TaskTideEngineObserver<<T extends TaskTideModel<T>>> <<engine-observer>> #F8DE7E {
    .. **Interface Methods** ..
    + {abstract} boolean onTaskStart(T)
    + {abstract} boolean onTaskProcessing(T)
    + {abstract} boolean onTaskEnd(T)
    + {abstract} List<WorkerObserver<T>> getObserver()
    + {abstract} WorkerObserver<T> getObserver(String)
}


' Uses ObserverResult
abstract org.tasktide.engine.observer.ObserverChain<T extends TaskTideModel<T>> <<implements engine-observer>> #FFE5B4 {
    .. **Attributes** ..
    # List<WorkerObserver<T>> observers

    .. **Construction** ..
    ObserverChain(<Observers>)

    .. **Interface Implementation** ..
    + boolean onTaskStart(T)
    + boolean onTaskProcessing(T)
    + boolean onTaskEnd(T)
}



class org.tasktide.engine.observer.chain.ItemTaskObserver <<extends ObserverChain>> #C6DAF7 {
    .. **Construction**..
    + ItemTaskObserver()
    + ItemTaskObserver(int timeKeeperTimeOut)

    .. **Interface Implementation** ..
    + List<WorkerObserver<ItemTask>> getObservers()
    + WorkerObserver<ItemTask> getObserver(String)
}


class org.tasktide.engine.observer.chain.WorkItemObserver <<extends ObserverChain>> #C6DAF7 {
    .. **Construction**..
    + WorkItemObserver()
    + WorkItemObserver(int timeKeeperTimeOut)

    .. **Interface Implementation** ..
    + List<WorkerObserver<WorkItem>> getObservers()
    + WorkerObserver<WorkItem> getObserver(String)
}


org.tasktide.engine.observer.ObserverChain ..|> org.tasktide.engine.observer.TaskTideEngineObserver
org.tasktide.engine.observer.chain.WorkItemObserver --|> org.tasktide.engine.observer.ObserverChain
org.tasktide.engine.observer.chain.ItemTaskObserver --|> org.tasktide.engine.observer.ObserverChain

org.tasktide.engine.observer.ObserverChain --> org.tasktide.engine.observer.ObserverResult
org.tasktide.engine.observer.TaskTideEngineObserver o-- org.tasktide.engine.observer.WorkerObserver


org.tasktide.engine.worker.executor.TaskTideExecutor --> org.tasktide.engine.observer.ObserverChain


/'
##################################################
##################################################
##
## c). Worker Observers
##
##################################################
##################################################
'/


interface org.tasktide.engine.observer.WorkerObserver<T extends TaskTideModel<T>> << worker-observer>> #F8DE7E {
    + ObserverResult onTaskStart(T)
    + ObserverResult onTaskProcessing(T)
    + ObserverResult onTaskEnd(T)
    + boolean isOptional()
    + ObserverType getType()
    + String getName()
}

class org.tasktide.engine.observer.ObserverResult {
    .. **Attributes** ..
    - boolean success
    - String failedObserver
    - ObserverType observerType
    - boolean canIgnore

    .. **Construction** ..
    ObserverResult(< All Attributes>)

    .. **Class Methods** ..
    + boolean isSuccess()
    + String getFailedObserver()
    + ObserverType getType()
    + boolean canIgnore()
    + static ObserverResult success()
    + static Observer failure(WorkerObserver)
    + staic Observer failure(WorkerObserver, boolean)
}

enum org.tasktide.engine.observer.worker.ObserverType #CCCCFF {
    .. **Enum Values** ..
    OPTIONAL, CRITICAL

    .. **Value Methods** ..
    + {abstract} boolean isType(ObserverType)
    + {abstract} boolean isType(String)
    + {abstract} boolean isOptional()
}


org.tasktide.engine.observer.WorkerObserver --> org.tasktide.engine.observer.ObserverResult
org.tasktide.engine.observer.WorkerObserver --> org.tasktide.engine.observer.ObserverType
org.tasktide.engine.observer.WorkerObserver *-- org.tasktide.engine.observer.ObserverResult



/'
##############################
##############################
##
## c). State Observer
##
##############################
##############################
'/


abstract org.tasktide.engine.observer.worker.StateObserver<T extends TaskTideModel> <<implements WorkerObserver>> #FFE5B4{
    .. **Attributes** ..
    - ObserverType type

    .. **Construction** ..
    StateObserver()

    .. **Partial Interface Implementation**..
    + boolean isOptional()
    + ObserverType getType()
}


class org.tasktide.engine.observer.worker.stateobserver.WorkItemStateObserver<WorkItem> <<extends StateObserver>> #C6DAF7 {
    .. **Construction** ..
    + WorkItemStateObserver()
    + WorkItemStateObserver(List<WorkItem>)

    .. **Interface Implementation** ..
    + ObserverResult onTaskStart(WorkItem)
    + ObserverResult onTaskProcessing(WorkItem)
    + ObserverResult onTaskEnd(WorkItem)
    + String getName()

    .. **Interface Decorators** ..
    - boolean verifyItem(WorkItem)
}


class org.tasktide.engine.observer.worker.stateobserver.ItemTaskStateObserver<ItemTask> <<extends StateObserver>> #C6DAF7 {
    .. **Construction** ..
    + ItemTaskStateObserver()
    + ItemTaskStateObserver(List<ItemTask>)

    .. **Interface Implementation** ..
    + ObserverResult onTaskStart(ItemTask)
    + ObserverResult onTaskProcessing(ItemTask)
    + ObserverResult onTaskEnd(ItemTask)
    + String getName()
}


org.tasktide.engine.observer.worker.StateObserver ..|> org.tasktide.engine.observer.WorkerObserver
org.tasktide.engine.observer.worker.stateobserver.WorkItemStateObserver --|> org.tasktide.engine.observer.worker.StateObserver
org.tasktide.engine.observer.worker.stateobserver.ItemTaskStateObserver --|> org.tasktide.engine.observer.worker.StateObserver


/'
##############################
##############################
##
## c). Executor Observer
##
##############################
##############################
'/


abstract org.tasktide.engine.observer.worker.ExecutorObserver<T extends TaskTideModel<T>, U extends TaskTideModel<U>> #FFE5B4 {
    .. **Attributes** ..
    - ObserverType type
    # Logger logger

    .. **Construction** ..
    ExecutorObserver()

    .. **Partial Interface Implementation**..
    + boolean isOptional()
    + ObserverType getType()
}

class org.tasktide.engine.observer.worker.executor.WorkItemExecutorObserver <<extends ExecutorObserver<WorkItem, ItemTask>> #C6DAF7 {
    .. **Construction** ..
    WorkItemExecutorObserver()

    .. **Interface Implementation**..
    + ObserverResult onTaskStart(WorkItem)
    + ObserverResult onTaskProcessing(WorkItem)
    + ObserverResult onTaskEnd(WorkItem)
    + String getName()

    .. **Interface Decorators**..
    + int handleUnlocks(WorkItem)
    + boolean pollUnitilDone(WorkItem)
    
}


org.tasktide.engine.observer.worker.ExecutorObserver ..|> org.tasktide.engine.observer.WorkerObserver
org.tasktide.engine.observer.worker.executor.WorkItemExecutorObserver --|> org.tasktide.engine.observer.worker.ExecutorObserver



/'
##############################
##############################
##
## c). TimeKeeper Observer
##
##############################
##############################
'/


abstract org.tasktide.engine.observer.worker.TimeKeeper<T extends TaskTideModel> <<implements WorkerObserver>> #FFE5B4 {
    .. **Attributes** ..
    # Logger logger
    - ObserverType type
    # AtomicBoolean abort
    # AtomicLong startTime
    # List<Long> executionTimes
    - long meanDuration

    .. **Construction** ..
    TimeKeeperObserver(long, Logger)

    .. **Interface Implementation**..
    + boolean isOptional()
    + ObserverType getType()
    + ObserverResult onTaskStart(T)
    + ObserverResult onTaskProcessing(T)
    + ObserverResult onTaskEnd(T)

    .. **Interface Decorator**..
    + {abstract} void handleTaskState(T, boolean)
    - boolean measureTime(long now, long startStamp)
    - void updateAbortFlag(boolean)
    - boolean evaluateStart(T, long now, long startStamp, long elpased)
    - boolean evaluateDuration(long now, long duration)
}


class org.tasktide.engine.observer.worker.timekeeper.WorkItemTimeKeeper<WorkItem> << extends TimeKeeperObserver >> #C6DAF7 {
    .. **Construction** ..
    + WorkItemTimeKeeper(long maxTime)

    .. **Interface Implementation**..
    + void handleTaskState(WorkItem, boolean)
    + String getName()
}

class org.tasktide.engine.observer.worker.timekeeper.ItemTaskTimeKeeper<ItemTask> << extends TimeKeeperObserver >> #C6DAF7 {
    .. **Construction** ..
    + ItemTaskTimeKeeper(long maxTime)

    .. **Interface Implementation**..
    + void handleTaskState(ItemTask, boolean)
    + String getName()
}


org.tasktide.engine.observer.worker.TimeKeeper ..|> org.tasktide.engine.observer.WorkerObserver
org.tasktide.engine.observer.worker.timekeeper.ItemTaskTimeKeeper --|> org.tasktide.engine.observer.worker.TimeKeeper
org.tasktide.engine.observer.worker.timekeeper.WorkItemTimeKeeper --|> org.tasktide.engine.observer.worker.TimeKeeper


/'
##################################################
##################################################
##
## d). Engine
##
##################################################
##################################################
'/



@enduml