@startuml


/'
################################################################
################################################################
##
## 2). TaskTide ItemStore
##
################################################################
################################################################
'/


class org.tasktide.itemstore.Item<T> {
  .. **Attributes** ..
  - String id, state, payload
  
  .. **Construction** ..
  + Item()
  + Item(String, String, String)

  .. **Getters & Setters** ..
  + void setId(String)
  + void setState(String)
  + void setPayload(String)
  + String getId()
  + String setState()
  + String setPayload()
}


interface org.tasktide.itemstore.ItemStore <<itemstore>> #F8DE7E {
  + {abstract} String getStoreName()
  + {abstract} String getMasterFilePath()
  + {abstract} String getFilePath()
  + {abstract} String getDbDirectory()

  + {abstract} void saveItem(Item) throws Exception
  + {abstract} void saveItems(List<Item>) throws Exception
  + {abstract} void saveItemToMaster(Item) throws Exception
  + {abstract} void saveItemsToMaster(List<Item>) throws Exception
  + {abstract} List<Item> getAll(boolean)
  + {abstract} Item getById(String) throws Exception
  + {abstract} Item getByIdFromMaster(String) throws Exception
  + {abstract} List<Item> getItemsByState(String) throws Exception
  + {abstract} List<Item> getItemsByStateFromMaster(String) throws Exception;
  + {abstract} String getPayloadById(String)
  + {abstract} String getPayloadFromMaster(String)
  + {abstract} void syncToMaster(Item) throws Exception
  + {abstract} void syncToMaster(List<Item>) throws Exception
  + {abstract} void syncToMaster() throws Exception
  + {abstract} boolean cacheMaster() throws Exception
  + {abstract} boolean clearPrototype()
  + {abstract} boolean closeConn(DbTarget)
  + {abstract} boolean openConn(DbTarget)
  + {abstract} boolean delete(Item) throws Exception
  + {abstract} boolean deleteFromMaster(Item) throws Exception
}


abstract class org.tasktide.itemstore.stores.AbstractItemStore <<implements itemstore>> #FFE5B4 {
  - String storeName
  - Path dbDirectory, masterDB
  - Path protoDB, masterLock
  - FileChannel fileChannel
  - FileLock fileLock
  - Random RANDOM
}


enum org.tasktide.itemstore.stores.DbTarget #CCCCFF {
    .. **Enum Values** ..
    MASTER, PROTOTYPE, BOTH
}


class org.tasktide.itemstore.stores.RocksDBStore << extends itemstore >> #C6DAF7 {
    .. **Attributes** ..
    - RocksDB master, proto
    - Options options
    - ObjectMapper MAPPER

    .. **Construction** ..
    + RocksDBStore(String, String, String, String)

    .. **Decorator Methods** ..
    + Item fetchIteratorValue(RocksIterator);
    
    .. **ItemStore Implementation** ..
    + List<Item> getAll(boolean)
    + void saveItemToMaster(Item)
    + void saveItemsToMaster(List<Item>)
    + void saveItem(Item)
    + void saveItems(List<Item>)
    + Item getById(String)
    + Item getByIdFromMaster(String)
    + List<Item> getItemsByState(String)
    + List<Item> getItemsByStateFromMaster(String)
    + String getPayloadById(String)
    + String getPayloadById(String)
    + boolean closeConn(DbTarget)
    + boolean openConn(DbTarget)
    + boolean delete(Item)
    + boolean deleteFromMaster(Item)
}


org.tasktide.itemstore.stores.AbstractItemStore ..|> org.tasktide.itemstore.ItemStore
org.tasktide.itemstore.stores.RocksDBStore --|> org.tasktide.itemstore.stores.AbstractItemStore
org.tasktide.itemstore.ItemStore --o org.tasktide.itemstore.Item
org.tasktide.itemstore.stores.AbstractItemStore --> org.tasktide.itemstore.stores.DbTarget

@enduml