plugins {
    id 'java'
}

description = 'tasktide:mutex'
group = 'org.tasktide'
version = '0.9.0'

dependencies { }


// Define test scopes
def parserTestTags = [
    "unit-tests": 'unit-mutex',
    "integration-tests": 'integration-mutex',
    "system-tests": 'system-mutex'
]


// Define logging scope for all tests
tasks.withType(Test).configureEach {
    testLogging {
        showStandardStreams = true
        events "passed", "skipped", "failed", "standardOut", "standardError"
        exceptionFormat "full"
    }
}


// Register test under annotation scheme
parserTestTags.each { name, tag ->
    tasks.register(name, Test) {
        group = 'mutex-tests'
        description = "Run Parser ${name} tests (${tag})"

        useJUnitPlatform {
            includeTags tag
        }
    }
}


jar {
    archiveBaseName.set("tasktide-${project.name}")
    archiveVersion.set(version)
}

task runLockApp(type: JavaExec) {
    group = 'application'
    description = 'Run LockActionReleaseApp with path argument'
    mainClass.set('org.tasktide.mutex.LockActionReleaseApp')
    classpath = sourceSets.test.runtimeClasspath
    args = ["/home/bren/testing/results.txt"]
}