plugins {
    id 'java'
}

description = 'tasktide:core'
group = 'org.tasktide.core'
version = '0.9.0'

dependencies {

    // TaskTide ItemStore Lib
    implementation project(':itemstore')

    // Jakarta-NoSQL
    implementation 'jakarta.nosql:jakarta.nosql-api:1.0.0'
    implementation "org.eclipse.jnosql.mapping:jnosql-mapping-document:1.1.8"
    implementation "org.eclipse.jnosql.mapping:jnosql-mapping-key-value:1.1.8"
    implementation "org.eclipse.jnosql.mapping:jnosql-mapping-column:1.1.8"
    implementation "org.eclipse.jnosql.mapping:jnosql-mapping-graph:1.1.8"

    // Jakarta-NoSQL Database Drivers
    implementation "org.eclipse.jnosql.databases:jnosql-mongodb:1.1.6"
    implementation "org.eclipse.jnosql.databases:jnosql-couchdb:1.1.6"
    implementation "org.eclipse.jnosql.databases:jnosql-arangodb:1.1.6"
    implementation "org.eclipse.jnosql.databases:jnosql-dynamodb:1.1.6"
    implementation "org.eclipse.jnosql.databases:jnosql-couchbase:1.1.6"
    implementation "org.eclipse.jnosql.databases:jnosql-redis:1.1.6"
    implementation "org.eclipse.jnosql.databases:jnosql-cassandra:1.1.6"

    // JPA
    implementation "jakarta.persistence:jakarta.persistence-api:3.1.0"
    implementation "org.hibernate.orm:hibernate-core:6.4.4.Final"
    implementation "com.zaxxer:HikariCP:5.1.0"
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jakarta-jsonp:2.19.2"
    testImplementation 'mysql:mysql-connector-java:8.0.33'
    
    // Host metrics
    implementation "com.github.oshi:oshi-core:6.8.3"
}

jar {
    archiveBaseName.set("tasktide-${project.name}")
    archiveVersion.set(version)
}