# Project
tasktideVersion=1.0.0
tasktideGroup=org.tasktide

# Module versions
mutexVersion=1.0.0
parserVersion=1.0.0
itemstoreVersion=1.0.0
coreVersion=1.0.0
engineVersion=1.0.0
apiVersion=1.0.0
# tasktideVersion=1.0.0 <- Client app brings the agg pom versioning deliverable-repo tied

# Publishing
tasktideURL=https://tasktide.org
tasktideSource=https://github.tasktide.org