# Project
tasktideVersion=0.9.10
tasktideGroup=org.tasktide

# Module versions
mutexVersion=0.9.9
parserVersion=0.9.9
itemstoreVersion=0.9.9
coreVersion=0.9.9
engineVersion=0.9.9
apiVersion=0.9.9
# tasktideVersion=0.9.10 <- Client app brings the agg pom versioning deliverable-repo tied

# Publishing
tasktideURL=https://tasktide.org
tasktideSource=https://github.tasktide.org