# Project
tasktideVersion=0.9.5
tasktideGroup=org.tasktide

# Module versions
mutexVersion=0.9.5
parserVersion=0.9.5
itemstoreVersion=0.9.5
coreVersion=0.9.5
engineVersion=0.9.5
apiVersion=0.9.5
# tasktideVersion=0.9.5 <- Client app brings the agg pom versioning deliverable-repo tied

# Publishing
tasktideURL=https://tasktide.org
tasktideSource=https://github.tasktide.org