plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1' // Apply Shadow plugin for Fat JAR
}

description = 'tasktide:tasktide'
group = 'org.tasktide.tasktide'
version = '0.0.1'

dependencies {

    // Project core lib
    implementation project(':core')
    implementation project(':engine')

    // Command-line argument parser
    implementation 'info.picocli:picocli:4.7.7'

    implementation 'jakarta.nosql:jakarta.nosql-api:1.0.0'
    implementation "org.eclipse.jnosql.mapping:jnosql-mapping-document:1.1.8"
    implementation "org.eclipse.jnosql.mapping:jnosql-mapping-key-value:1.1.8"
    implementation "org.eclipse.jnosql.mapping:jnosql-mapping-column:1.1.8"
    implementation "org.eclipse.jnosql.mapping:jnosql-mapping-graph:1.1.8"
}

jar {
    archiveBaseName.set("tasktide-${project.name}")
    archiveVersion.set(version)
}

tasks.register('fatJar', com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar) {
    archiveBaseName.set("tasktide-${project.name}")
    archiveVersion.set(version)
    archiveClassifier.set('all')
    configurations = [project.configurations.runtimeClasspath]
}

build.dependsOn fatJar