apply plugin: 'maven-publish'

group = 'org.tasktide'

publishing {
    publications {
        mavenAggregator(MavenPublication) {
            pom {
                name = 'TaskTide'
                description = 'TaskTide libraries'
                packaging = 'pom'

                apply from: "$rootDir/gradle/pom.gradle"

                withXml {
                    def dependenciesNode = asNode().appendNode('dependencies')

                    [
                        project(':api'),
                        project(':engine'),
                        project(':core'),
                        project(':itemstore'),
                        project(':parser'),
                        project(':mutex')
                    ].each { dependencyProject ->
                        def dependency = dependenciesNode.appendNode('dependency')

                        dependency.appendNode('groupId', dependencyProject.group)
                        dependency.appendNode(
                            'artifactId',
                            "tasktide-${dependencyProject.name}"
                        )
                        dependency.appendNode(
                            'version',
                            dependencyProject.version
                        )
                    }
                }
            }
        }S
    }
}