name: TaskTide CI Workflow

permissions:
  contents: read

on:
  workflow_dispatch:


jobs:

  # Assemble main project
  assemble:
    uses: ./.github/workflows/assemble.yml


  # Detect libraries to for testing
  detect:
    needs: assemble
    uses: ./.github/workflows/_detect.yml


  # Build and test library strategy matrix
  library:
    needs: detect
    uses: ./.github/workflows/_library.yml
    with:
      library: ${{ matrix.library }}
    if: needs.detect.outputs.libraries != '[]'
    strategy:
      fail-fast: false
      matrix:
        library: ${{ fromJSON(needs.detect.outputs.libraries )}}


  # Publish to dockerhub
  dockerPublish:
    needs: library
    if: github.ref == 'refs/tags/for-publish'
    uses:
      ./.github/workflows/_dockerHub.yml


  # Publish to maven
  mavenPublish:
    needs: library
    if: github.ref == 'refs/tags/for-publish'
    uses:
      ./.github/workflows/_maven.yml
