name: TaskTide CI Workflow

permissions:
  contents: read

on:
  workflow_dispatch:

  push:
    branches:
      - main
    
    tags:
       - 'v*.*.*'

    paths:
      - 'tasktide/**'
      - '.github/workflows/**'

  pull_request:
    branches:
      - main
    paths:
      - 'tasktide/**'
      - '.github/workflows/**'


jobs:

  # Assemble main project
  assemble:
    uses: ./.github/workflows/tasktide-ci-assembly.yml


  # Detect libraries to for testing
  detect:
    needs: assemble
    uses: ./.github/workflows/tasktide-ci-detect-updated-module.yml


  # Build and test library strategy matrix
  build:
    needs: detect
    uses: ./.github/workflows/tasktide-ci-test-library.yml
    with:
      library: ${{ matrix.library }}
    if: needs.detect.outputs.libraries != '[]'
    strategy:
      fail-fast: false
      matrix:
        library: ${{ fromJSON(needs.detect.outputs.libraries )}}


  # Publish to dockerhub
  dockerPublish:
    needs: build
    if: github.ref == 'refs/tags/for-publish'
    uses:
      ./.github/workflows/tasktide-ci-dockerHub-publish.yml


  # Publish to maven
  mavenPublish:
    needs: build
    if: github.ref == 'refs/tags/for-publish'
    uses:
      ./.github/workflows/tasktide-ci-maven-publish.yml
