name: TaskTide-CD Maven and DockerHub


permissions:
  contents: read


on:
  workflow_dispatch:


jobs:

  # Publish docker image
  dockerHub:
    uses: ./.github/workflows/tasktide-cd-dockerHub-publish.yml
    secrets: inherit


  # Publish maven artifacts
  mavenCentral:
    uses: ./.github/workflows/tasktide-cd-maven-publish.yml
    secrets: inherit