name: TaskTide-CI DockerHub Publish

permissions:
  contents: read

on:
  workflow_call:
  workflow_dispatch:


jobs:
  publishToDockerHub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0


      - name: Configure docker build
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          cd tasktide
          echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          ./gradlew build -x test
          cp tasktide/build/distributions/tasktide*.zip ../docker/tasktide.zip


      - name: Build and Publish Latest Image
        env:
          VERSION_TAG: ${{ github.ref_name }}
        run: |
          cd ./docker
          docker build -t bkenna/tasktide -f tasktide-latest.Dockerfile .
          docker push bkenna/tasktide

          docker tag bkenna/tasktide bkenna/tasktide:${VERSION_TAG}
          docker push bkenna/tasktide:${VERSION_TAG}



      - name: Build and Publish Apptainer Image
        env:
          VERSION_TAG: ${{ github.ref_name }}
        run: |
          cd ./docker
          docker build -t bkenna/tasktide_apptainer -f tasktide-apptainer.Dockerfile .
          docker push bkenna/tasktide_apptainer

          docker tag bkenna/tasktide_apptainer bkenna/tasktide_apptainer:${VERSION_TAG}
          docker push bkenna/tasktide_apptainer:${VERSION_TAG}

