plugins {
    id 'java'
}

description = 'tasktide:parser'
group = 'org.tasktide'
version = '0.9.1'

dependencies {
    // Mutex sub-project
    implementation project(":mutex")
}


// Define test scopes
def testTags = [
    "unit-tests": 'unit-parser',
    "integration-tests": 'integration-parser',
    "system-tests": 'system-parser'
]


// Define logging scope for all tests
tasks.withType(Test).configureEach {
    testLogging {
        showStandardStreams = true
        events "passed", "skipped", "failed", "standardOut", "standardError"
        exceptionFormat "full"
    }
}


// Register test under annotation scheme
testTags.each { name, tag ->
    tasks.register(name, Test) {
        group = 'parser-tests'
        description = "Run Parser ${name} tests (${tag})"

        useJUnitPlatform {
            includeTags tag
        }
    }
}


jar {
    archiveBaseName.set("tasktide-${project.name}")
    archiveVersion.set(version)
}